#!/bin/bash

# Purpose:  configure and run the amazon mail setup

set -e
set -u

hostname > /etc/mailname

postconf -e "myhostname = `hostname`"
postconf -e "mynetworks = $NETWORKS"
postconf -e "append_dot_mydomain = $DOMAIN"
postconf -e "remote_header_rewrite_domain = $DOMAIN"

postconf -e "relayhost = $SES_ENDPOINT:587"
echo "$SES_ENDPOINT:587 $ID:$KEY" > /etc/postfix/sasl-passwords
postmap hash:/etc/postfix/sasl-passwords

# Various services needed
service rsyslog start
service cron start
service postfix start

if [ -n "$*" ] ; then
    eval "$@"
else
    # Run forever
    while true;
      do 
	sleep 100d
    done
fi